# Generated by Django 5.2.5 on 2025-09-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_role_customuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
