# Generated by Django 5.2.5 on 2025-09-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='likes',
            field=models.IntegerField(default=0, help_text='点赞量'),
        ),
        migrations.AddField(
            model_name='issue',
            name='views',
            field=models.IntegerField(default=0, help_text='浏览量'),
        ),
    ]
