# Generated by Django 5.2.5 on 2025-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_issue_likes_issue_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='attachment',
            field=models.FileField(blank=True, help_text='附件', null=True, upload_to='attachments/'),
        ),
    ]
