# Generated by Django 5.2.5 on 2025-09-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_issue_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(default='已提交，等待审核', null=True),
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
