# Generated by Django 5.2.5 on 2025-09-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_reply_attachment_issuelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='popularity',
            field=models.FloatField(default=0.0, help_text='热度值'),
        ),
    ]
