# Generated by Django 5.2.5 on 2025-09-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_issue_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
