# Generated by Django 5.2.5 on 2025-09-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_reply_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='attachment',
            field=models.FileField(blank=True, help_text='附件', null=True, upload_to='attachments/'),
        ),
    ]
